import Images from '../../../Images/index'
export const initialProductData = [{
    id: '1',
    title: 'CHAIR',
    description: 'Minimal LCD chair',
    newPrice: 180,
    oldPrice: 250,
    img: Images.product6,
  },
  {
    id: '2',
    title: 'SOFA',
    description: 'Modern Sofa',
    newPrice: 120,
    oldPrice: 150,
    img: Images.product1,
  },
  {
    id: '3',
    title: 'SOFA',
    description: 'Microfiber Sofa',
    newPrice: 130,
    oldPrice: 150,
    img: Images.product2,
  },
  {
    id: '4',
    title: 'TABBLE',
    description: 'Wood Cofee Tables',
    newPrice: 100,
    oldPrice: 120,
    img: Images.product3,
  },
  {
    id: '5',
    title: 'CHAIR',
    description: 'Acacia Wood Club Chairs',
    newPrice: 100,
    oldPrice: 120,
    img: Images.product4,
  },
  {
    id: '6',
    title: 'BENCH',
    description: 'Amalia Cowhide Bench',
    newPrice: 130,
    oldPrice: 150,
    img: Images.product5,
  },
  {
    id: '7',
    title: 'STORAGE',
    description: 'Juno-Hinged Lid Storage',
    newPrice: 180,
    oldPrice: 250,
    img: Images.product7,
  },
  {
    id: '8',
    title: 'FURNITURE',
    description: 'Delicia 3 Piece Living Room',
    newPrice: 120,
    oldPrice: 150,
    img: Images.product8,
  }]